//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class aircontry
    {
        public string chinese_city { get; set; }
        public string eng_city { get; set; }
        public string shortform { get; set; }
        public string airport_name { get; set; }
    }
}
