//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class airline
    {
        public airline()
        {
            this.flightclasses = new HashSet<flightclass>();
        }
    
        public string AirlineCode { get; set; }
        public string Password { get; set; }
        public string airlineName { get; set; }
        public string icon { get; set; }
    
        public virtual ICollection<flightclass> flightclasses { get; set; }
    }
}
