//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class attractbooking
    {
        public attractbooking()
        {
            this.vehiclebookings = new HashSet<vehiclebooking>();
        }
    
        public int BookID { get; set; }
        public string Attaction { get; set; }
        public string City { get; set; }
        public int adultPrice { get; set; }
        public int childPrice { get; set; }
        public int adultNum { get; set; }
        public int childNum { get; set; }
        public int TotalAmt { get; set; }
        public string staffID { get; set; }
        public string custID { get; set; }
        public System.DateTime orderDate { get; set; }
        public string status { get; set; }
    
        public virtual attraction attraction { get; set; }
        public virtual customer customer { get; set; }
        public virtual staff staff { get; set; }
        public virtual ICollection<vehiclebooking> vehiclebookings { get; set; }
    }
}
