//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class attraction
    {
        public attraction()
        {
            this.attractbookings = new HashSet<attractbooking>();
            this.attractprices = new HashSet<attractprice>();
        }
    
        public string AttractName { get; set; }
        public string Duration { get; set; }
        public string Cancellation { get; set; }
        public string AttractPhoto { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<attractbooking> attractbookings { get; set; }
        public virtual ICollection<attractprice> attractprices { get; set; }
    }
}
