//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class cruiseorganizer
    {
        public cruiseorganizer()
        {
            this.cruises = new HashSet<cruise>();
        }
    
        public int OrganID { get; set; }
        public string OrganizerE { get; set; }
        public string OrganizerC { get; set; }
    
        public virtual ICollection<cruise> cruises { get; set; }
    }
}
