//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.attractbookings = new HashSet<attractbooking>();
            this.cruisebookings = new HashSet<cruisebooking>();
            this.flightbookings = new HashSet<flightbooking>();
            this.hotelbookings = new HashSet<hotelbooking>();
        }
    
        public string CustID { get; set; }
        public string Surname { get; set; }
        public string GivenName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Passport { get; set; }
        public string MobileNo { get; set; }
        public string Nationality { get; set; }
    
        public virtual ICollection<attractbooking> attractbookings { get; set; }
        public virtual ICollection<cruisebooking> cruisebookings { get; set; }
        public virtual ICollection<flightbooking> flightbookings { get; set; }
        public virtual ICollection<hotelbooking> hotelbookings { get; set; }
    }
}
