//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public hotel()
        {
            this.rooms = new HashSet<room>();
        }
    
        public int HotelID { get; set; }
        public string Password { get; set; }
        public string ChiName { get; set; }
        public string EngName { get; set; }
        public Nullable<decimal> Star { get; set; }
        public decimal Rating { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
    
        public virtual ICollection<room> rooms { get; set; }
    }
}
