//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotelbooking
    {
        public int BookingID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string StaffID { get; set; }
        public string CustID { get; set; }
        public int HotelID { get; set; }
        public string RoomType { get; set; }
        public decimal Price { get; set; }
        public int RoomSize { get; set; }
        public decimal TotalAmt { get; set; }
        public System.DateTime Checkin { get; set; }
        public System.DateTime Checkout { get; set; }
        public string Remark { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual room room { get; set; }
        public virtual staff staff { get; set; }
    }
}
