//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class attractprice
    {
        public string AttractName { get; set; }
        public int ChildPrice { get; set; }
        public int AdultPrice { get; set; }
    
        public virtual attraction attraction { get; set; }
    }
}
