//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class cruise
    {
        public cruise()
        {
            this.cruisebookings = new HashSet<cruisebooking>();
        }
    
        public string CruiseNo { get; set; }
        public string CruiseName { get; set; }
        public int RefPrice { get; set; }
        public int TourDay { get; set; }
        public int OrganID { get; set; }
        public System.DateTime StartDate { get; set; }
        public string pdf { get; set; }
    
        public virtual cruiseorganizer cruiseorganizer { get; set; }
        public virtual ICollection<cruisebooking> cruisebookings { get; set; }
    }
}
