//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class cruisebooking
    {
        public int BookingID { get; set; }
        public string cruiseNo { get; set; }
        public string cruiseName { get; set; }
        public int TourDay { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ChildNum { get; set; }
        public int AdultNum { get; set; }
        public decimal ChildPrice { get; set; }
        public int AdultPrice { get; set; }
        public decimal TotalAmt { get; set; }
        public string staffID { get; set; }
        public string custID { get; set; }
        public System.DateTime orderDate { get; set; }
    
        public virtual cruise cruise { get; set; }
        public virtual customer customer { get; set; }
        public virtual staff staff { get; set; }
    }
}
