//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverroster
    {
        public string StaffID { get; set; }
        public int Timeslot { get; set; }
        public string Available { get; set; }
    
        public virtual driver driver { get; set; }
    }
}
