//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class flightschedule
    {
        public string FlightNo { get; set; }
        public System.DateTime DepDateTime { get; set; }
        public System.DateTime ArrDateTime { get; set; }
        public string DepAirport { get; set; }
        public string ArrAirport { get; set; }
        public int FlyMinute { get; set; }
        public string Aircraft { get; set; }
    }
}
