//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class flightclass
    {
        public flightclass()
        {
            this.flightbookings = new HashSet<flightbooking>();
        }
    
        public string FlightNo { get; set; }
        public string Class { get; set; }
        public string AirlineCode { get; set; }
        public int Price_Adult { get; set; }
        public int Price_Children { get; set; }
        public int Price_Infant { get; set; }
        public decimal Tax { get; set; }
    
        public virtual airline airline { get; set; }
        public virtual ICollection<flightbooking> flightbookings { get; set; }
    }
}
