//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.attractbookings = new HashSet<attractbooking>();
            this.cruisebookings = new HashSet<cruisebooking>();
            this.flightbookings = new HashSet<flightbooking>();
            this.hotelbookings = new HashSet<hotelbooking>();
        }
    
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public string Gender { get; set; }
        public string Center { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string Position { get; set; }
        public int Salary { get; set; }
        public string Ctype { get; set; }
        public Nullable<int> Late { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<attractbooking> attractbookings { get; set; }
        public virtual ICollection<cruisebooking> cruisebookings { get; set; }
        public virtual ICollection<flightbooking> flightbookings { get; set; }
        public virtual ICollection<hotelbooking> hotelbookings { get; set; }
    }
}
