//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiclebooking
    {
        public vehiclebooking()
        {
            this.equipmentlists = new HashSet<equipmentlist>();
        }
    
        public string Vehicle_ID { get; set; }
        public int AttractionBookingID { get; set; }
        public int BookDay { get; set; }
        public decimal VehicleBookPrice { get; set; }
        public int VehicleBookingID { get; set; }
        public System.DateTime Orderdate { get; set; }
    
        public virtual attractbooking attractbooking { get; set; }
        public virtual ICollection<equipmentlist> equipmentlists { get; set; }
        public virtual vehicle vehicle { get; set; }
    }
}
